import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';

import '../../../../core/errors/app_failure.dart';
import '../../../../core/extensions/build_context_x.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../../core/utils/app_logger.dart';
import '../../../../core/widgets/app_badge.dart';
import '../../../../core/widgets/app_button.dart';
import '../../../../core/widgets/app_card.dart';
import '../../../../core/widgets/app_empty_state.dart';
import '../../../../core/widgets/app_error_state.dart';
import '../../../../core/widgets/app_snackbar.dart';
import '../../../../data/repositories/supabase_product_repository.dart';
import '../../../../domain/models/business_settings.dart';
import '../../../../domain/models/product.dart';
import '../../labels/data/label_pdf_builder.dart';
import '../../labels/domain/label_sheet_spec.dart';
import '../../products/application/product_list_controller.dart';
import '../../settings/application/business_settings_controller.dart';

/// Local format option definition for UI selection.
class _FormatOption {
  const _FormatOption({
    required this.id,
    required this.title,
    required this.sub1,
    required this.sub2,
    required this.icon,
  });

  final String id;
  final String title;
  final String sub1;
  final String sub2;
  final IconData icon;
}

const List<_FormatOption> _kFormatOptions = <_FormatOption>[
  _FormatOption(
    id: 'thermal',
    title: 'Thermal Label',
    sub1: '50 × 25 mm',
    sub2: 'Continuous roll',
    icon: Icons.label_outlined,
  ),
  _FormatOption(
    id: 'a4_24',
    title: 'A4 Sheet',
    sub1: '24 labels',
    sub2: '70 × 37 mm',
    icon: Icons.grid_view_rounded,
  ),
  _FormatOption(
    id: 'a4_65',
    title: 'A4 Sheet',
    sub1: '65 labels',
    sub2: '38.1 × 21.2 mm',
    icon: Icons.apps_rounded,
  ),
];

final productQrLabelsProvider =
    FutureProvider.family<List<String>, String>((ref, productId) async {
  final repo = ref.watch(productRepositoryProvider);
  final res = await repo.fetchQrLabels(productId);
  return res.fold(
    onSuccess: (labels) => labels,
    onFailure: (_) => <String>[],
  );
});

/// The dedicated Admin Print Labels page for sequential product label control.
class PrintLabelsPage extends ConsumerStatefulWidget {
  /// Creates the page.
  const PrintLabelsPage({super.key});

  @override
  ConsumerState<PrintLabelsPage> createState() => _PrintLabelsPageState();
}

class _PrintLabelsPageState extends ConsumerState<PrintLabelsPage> {
  String _selectedFormatId = 'thermal';
  String? _selectedProductId;
  bool _isPrinting = false;

  LabelSheetSpec get _selectedSpec {
    return switch (_selectedFormatId) {
      'a4_24' => LabelSheets.a4TwentyFourUp,
      'a4_65' => LabelSheets.a4SixtyFiveUp,
      _ => LabelSheets.thermalFiftyByTwentyFive,
    };
  }

  Future<void> _printNewLabels(Product product, int availableCount) async {
    if (_isPrinting) return;
    if (availableCount <= 0) {
      AppSnackbar.error(context, 'No new labels available to print.');
      return;
    }

    setState(() => _isPrinting = true);
    try {
      // 1. Allocate and persist new QR labels in database
      final allocResult = await ref
          .read(productRepositoryProvider)
          .allocateQrLabels(product.id, availableCount);

      final serials = allocResult.fold(
        onSuccess: (list) => list,
        onFailure: (err) => throw err,
      );

      if (serials.isEmpty) {
        throw Exception('No labels generated by server.');
      }

      // 2. Fetch business settings
      BusinessSettings business;
      try {
        business = await ref.read(businessSettingsControllerProvider.future);
      } catch (_) {
        business = const BusinessSettings(businessName: 'Maruti Water Solution');
      }

      // 3. Build PDF with newly allocated QR codes
      final pdfBytes = await LabelPdfBuilder.build(
        items: <LabelJobItem>[
          LabelJobItem(
            product: product,
            serialNumbers: serials,
          ),
        ],
        spec: _selectedSpec,
        business: business,
      );

      // 4. Refresh label list & product list
      ref.invalidate(productQrLabelsProvider(product.id));
      await ref.read(productListControllerProvider.notifier).refresh();

      if (!mounted) return;

      // 5. Open print dialog
      await Printing.layoutPdf(
        onLayout: (format) async => pdfBytes,
        name: '${product.productCode}_NewLabels_${serials.first}_${serials.last}',
      );
    } catch (error, stackTrace) {
      AppLog.error('Printing new labels failed', error, stackTrace);
      if (mounted) {
        AppSnackbar.error(context, 'Unable to print labels. Please try again.');
      }
    } finally {
      if (mounted) {
        setState(() => _isPrinting = false);
      }
    }
  }

  Future<void> _printAllLabels(Product product, List<String> existingLabels) async {
    if (_isPrinting) return;
    if (existingLabels.isEmpty) {
      AppSnackbar.error(context, 'No existing labels found to print.');
      return;
    }

    setState(() => _isPrinting = true);
    try {
      BusinessSettings business;
      try {
        business = await ref.read(businessSettingsControllerProvider.future);
      } catch (_) {
        business = const BusinessSettings(businessName: 'Maruti Water Solution');
      }

      final pdfBytes = await LabelPdfBuilder.build(
        items: <LabelJobItem>[
          LabelJobItem(
            product: product,
            serialNumbers: existingLabels,
          ),
        ],
        spec: _selectedSpec,
        business: business,
      );

      if (!mounted) return;

      await Printing.layoutPdf(
        onLayout: (format) async => pdfBytes,
        name: '${product.productCode}_AllLabels_1_${existingLabels.length}',
      );
    } catch (error, stackTrace) {
      AppLog.error('Printing all labels failed', error, stackTrace);
      if (mounted) {
        AppSnackbar.error(context, 'Unable to print labels. Please try again.');
      }
    } finally {
      if (mounted) {
        setState(() => _isPrinting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final listState = ref.watch(productListControllerProvider);

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.actionPrintLabels),
      ),
      body: SafeArea(
        child: listState.when(
          loading: () => const Center(
            child: CircularProgressIndicator(),
          ),
          error: (Object error, StackTrace stackTrace) => AppErrorState(
            failure: error is AppFailure
                ? error
                : UnexpectedFailure(cause: error, stackTrace: stackTrace),
            onRetry: () =>
                ref.read(productListControllerProvider.notifier).refresh(),
          ),
          data: (ProductListState state) {
            if (state.products.isEmpty) {
              return AppEmptyState(
                icon: Icons.inventory_2_outlined,
                title: l10n.productsEmptyTitle,
                message: l10n.productsEmptyBody,
              );
            }
            return _buildContent(context, state.products);
          },
        ),
      ),
    );
  }

  Widget _buildContent(BuildContext context, List<Product> products) {
    // Select first product if none currently selected
    final selectedProduct = products.where((p) => p.id == _selectedProductId).firstOrNull ?? products.first;
    _selectedProductId = selectedProduct.id;

    final labelsAsync = ref.watch(productQrLabelsProvider(selectedProduct.id));
    final existingLabels = labelsAsync.valueOrNull ?? <String>[];
    final existingLabelsCount = existingLabels.length;

    final stock = selectedProduct.stockQuantity ?? (selectedProduct.inStock ? 1 : 0);
    final newLabelsAvailable = (stock - existingLabelsCount).clamp(0, stock);

    final prefix = selectedProduct.productCode;
    final newLabelsPreview = <String>[];
    for (var i = 1; i <= newLabelsAvailable; i++) {
      newLabelsPreview.add('$prefix-${(existingLabelsCount + i).toString().padLeft(3, '0')}');
    }

    final newPreviewText = newLabelsPreview.isEmpty
        ? 'No new labels available'
        : (newLabelsPreview.length == 1
            ? newLabelsPreview.first
            : '${newLabelsPreview.first}\n→\n${newLabelsPreview.last}');

    final allPreviewText = existingLabels.isEmpty
        ? 'None'
        : (existingLabels.length == 1
            ? existingLabels.first
            : '${existingLabels.first} → ${existingLabels.last}');

    return ListView(
      padding: const EdgeInsets.symmetric(
        horizontal: Spacing.x4,
        vertical: Spacing.x3,
      ),
      children: <Widget>[
        _buildSectionHeader(context, '1. SELECT PRODUCT'),
        const SizedBox(height: Spacing.x2),
        _buildProductDropdown(products, selectedProduct),
        const SizedBox(height: Spacing.x6),
        _buildSectionHeader(context, '2. STOCK & LABEL INFORMATION'),
        const SizedBox(height: Spacing.x2),
        _buildProductInfoCard(context, selectedProduct, existingLabelsCount, newLabelsAvailable),
        const SizedBox(height: Spacing.x6),
        _buildSectionHeader(context, '3. LABEL FORMAT'),
        const SizedBox(height: Spacing.x2),
        _buildFormatOptions(),
        const SizedBox(height: Spacing.x6),
        _buildSectionHeader(context, '4. PRINT ACTIONS'),
        const SizedBox(height: Spacing.x2),
        _buildPrintActionsCard(
          context,
          selectedProduct,
          existingLabels,
          newLabelsAvailable,
          existingLabelsCount,
          newPreviewText,
          allPreviewText,
        ),
        const SizedBox(height: Spacing.x8),
      ],
    );
  }

  Widget _buildSectionHeader(BuildContext context, String title) {
    return Text(
      title,
      style: context.textTheme.labelMedium?.copyWith(
        color: AppColors.textSecondary,
        fontWeight: FontWeight.bold,
        letterSpacing: 1.1,
      ),
    );
  }

  Widget _buildProductDropdown(List<Product> products, Product selectedProduct) {
    return AppCard(
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: selectedProduct.id,
          isExpanded: true,
          icon: const Icon(Icons.keyboard_arrow_down_rounded, color: AppColors.primary),
          items: products.map((Product product) {
            return DropdownMenuItem<String>(
              value: product.id,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                    product.name,
                    style: const TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                      color: AppColors.ink,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                  Text(
                    '${product.productCode} • Stock: ${product.availableStock} pcs',
                    style: const TextStyle(
                      fontSize: 12,
                      color: AppColors.textSecondary,
                      fontFamily: 'monospace',
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
          onChanged: _isPrinting
              ? null
              : (String? newId) {
                  if (newId != null && newId != _selectedProductId) {
                    setState(() {
                      _selectedProductId = newId;
                    });
                  }
                },
        ),
      ),
    );
  }

  Widget _buildProductInfoCard(
    BuildContext context,
    Product product,
    int existingCount,
    int newAvailable,
  ) {
    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      product.name,
                      style: context.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                        color: AppColors.ink,
                      ),
                    ),
                    const SizedBox(height: Spacing.x1),
                    Text(
                      product.productCode,
                      style: context.textTheme.bodyMedium?.copyWith(
                        color: AppColors.primary,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'monospace',
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: BoxDecoration(
                  color: AppColors.primaryTint,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  product.category.name.toUpperCase(),
                  style: context.textTheme.bodySmall?.copyWith(
                    color: AppColors.primaryDark,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const Divider(height: Spacing.x6),
          Row(
            children: <Widget>[
              _buildStatBox(
                context,
                title: 'Current Stock',
                value: '${product.availableStock}',
                subtitle: 'in inventory',
                color: AppColors.ink,
              ),
              const SizedBox(width: Spacing.x2),
              _buildStatBox(
                context,
                title: 'Existing Labels',
                value: '$existingCount',
                subtitle: 'already allocated',
                color: AppColors.primaryDark,
              ),
              const SizedBox(width: Spacing.x2),
              _buildStatBox(
                context,
                title: 'New Labels Avail.',
                value: '$newAvailable',
                subtitle: newAvailable > 0 ? 'ready to print' : 'up to date',
                color: newAvailable > 0 ? AppColors.success : AppColors.textSecondary,
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildStatBox(
    BuildContext context, {
    required String title,
    required String value,
    required String subtitle,
    required Color color,
  }) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(Spacing.x3),
        decoration: BoxDecoration(
          color: AppColors.surface,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: AppColors.border),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(
              title,
              style: context.textTheme.bodySmall?.copyWith(
                color: AppColors.textSecondary,
                fontSize: 11,
              ),
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
            const SizedBox(height: Spacing.x1),
            Text(
              value,
              style: context.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
                color: color,
              ),
            ),
            const SizedBox(height: 2),
            Text(
              subtitle,
              style: context.textTheme.bodySmall?.copyWith(
                color: AppColors.textSecondary,
                fontSize: 10,
              ),
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFormatOptions() {
    return Column(
      children: _kFormatOptions.map((option) {
        final isSelected = option.id == _selectedFormatId;
        return Padding(
          padding: const EdgeInsets.only(bottom: Spacing.x2),
          child: AppCard(
            isSelected: isSelected,
            onTap: _isPrinting
                ? null
                : () => setState(() {
                      _selectedFormatId = option.id;
                    }),
            child: Row(
              children: <Widget>[
                Radio<String>(
                  value: option.id,
                  groupValue: _selectedFormatId,
                  onChanged: _isPrinting
                      ? null
                      : (val) {
                          if (val != null) {
                            setState(() {
                              _selectedFormatId = val;
                            });
                          }
                        },
                  activeColor: AppColors.primary,
                ),
                const SizedBox(width: Spacing.x2),
                Icon(
                  option.icon,
                  color: isSelected ? AppColors.primary : AppColors.textSecondary,
                  size: 22,
                ),
                const SizedBox(width: Spacing.x3),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        option.title,
                        style: context.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                          color: AppColors.ink,
                        ),
                      ),
                      const SizedBox(height: Spacing.x1),
                      Text(
                        '${option.sub1} • ${option.sub2}',
                        style: context.textTheme.bodySmall?.copyWith(
                          color: AppColors.textSecondary,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildPrintActionsCard(
    BuildContext context,
    Product product,
    List<String> existingLabels,
    int newAvailable,
    int existingCount,
    String newPreviewText,
    String allPreviewText,
  ) {
    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          if (newAvailable > 0) ...<Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text(
                  'New Labels Available:',
                  style: context.textTheme.labelMedium?.copyWith(
                    color: AppColors.ink,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                AppBadge(
                  label: '$newAvailable labels ready',
                  tone: AppBadgeTone.success,
                ),
              ],
            ),
            const SizedBox(height: Spacing.x3),
            Container(
              padding: const EdgeInsets.all(Spacing.x3),
              decoration: BoxDecoration(
                color: AppColors.primaryTint,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Row(
                    children: <Widget>[
                      const Icon(Icons.qr_code_2_rounded, size: 18, color: AppColors.primaryDark),
                      const SizedBox(width: Spacing.x2),
                      Text(
                        'Will print ($newAvailable labels):',
                        style: context.textTheme.bodySmall?.copyWith(
                          color: AppColors.primaryDark,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: Spacing.x2),
                  Text(
                    newPreviewText,
                    style: context.textTheme.bodyMedium?.copyWith(
                      color: AppColors.primaryDark,
                      fontWeight: FontWeight.bold,
                      fontFamily: 'monospace',
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: Spacing.x4),
            AppButton(
              label: 'Print New Labels ($newAvailable)',
              icon: Icons.print_rounded,
              isLoading: _isPrinting,
              onPressed: _isPrinting ? null : () => _printNewLabels(product, newAvailable),
            ),
          ] else ...<Widget>[
            Container(
              padding: const EdgeInsets.all(Spacing.x4),
              decoration: BoxDecoration(
                color: AppColors.surface,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppColors.border),
              ),
              child: Row(
                children: <Widget>[
                  const Icon(Icons.check_circle_outline_rounded, color: AppColors.success, size: 20),
                  const SizedBox(width: Spacing.x3),
                  Expanded(
                    child: Text(
                      'All labels for current stock capacity have been generated. Adding product stock will unlock new sequential labels.',
                      style: context.textTheme.bodySmall?.copyWith(
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
          const Divider(height: Spacing.x6),
          Text(
            'REPRINT EXISTING SERIES',
            style: context.textTheme.labelSmall?.copyWith(
              color: AppColors.textSecondary,
              fontWeight: FontWeight.bold,
              letterSpacing: 1.1,
            ),
          ),
          const SizedBox(height: Spacing.x2),
          Text(
            'Complete tracked series: $allPreviewText ($existingCount labels)',
            style: context.textTheme.bodySmall?.copyWith(
              color: AppColors.textSecondary,
              fontFamily: 'monospace',
            ),
          ),
          const SizedBox(height: Spacing.x3),
          AppButton(
            label: 'Print All Labels ($existingCount)',
            icon: Icons.replay_rounded,
            variant: AppButtonVariant.secondary,
            isLoading: _isPrinting,
            onPressed: (_isPrinting || existingCount == 0)
                ? null
                : () => _printAllLabels(product, existingLabels),
          ),
        ],
      ),
    );
  }
}
